export enum ScriptType {
    TriggerNamed = 'trigger_named',
    UpdateTouchBarWidget = 'update_touch_bar_widget',
    TriggerAction = 'trigger_action',
    ExecuteAssignedActionsForTrigger = 'execute_assigned_actions_for_trigger',
    RefreshWidget = 'refresh_widget',
    UpdateTrigger = 'update_trigger',
    AddNewTrigger = 'add_new_trigger',
    DeleteTrigger = 'delete_trigger',
    SetPersistentStringVariable = 'set_persistent_string_variable',
    SetStringVariable = 'set_string_variable',
    GetStringVariable = 'get_string_variable',
    SetPersistentNumberVariable = 'set_persistent_number_variable',
    SetNumberVariable = 'set_number_variable',
    GetNumberVariable = 'get_number_variable',
}

export enum ImageSearchOn {
    All = 0,
    CurrentMonitor = 1,
    FocusedWindow = 5
}

export enum ImageSearchRegion {
    All = 0,
    TopLeft = 1,
    BottomLeft = 3,
    BottomRight = 4,
    TopHalf = 5,
    BottomHalf = 6
}

export enum BttKeyCode {
    a = '0',
    b = '11',
    c = '8',
    C = '8',
    d = '2',
    e = '14',
    f = '3',
    g = '5',
    h = '4',
    i = '34',
    j = '38',
    k = '40',
    l = '37',
    m = '46',
    n = '45',
    o = '31',
    O = '31',
    p = '35',
    P = '35',
    q = '12',
    r = '15',
    s = '1',
    S = '1',
    t = '17',
    u = '32',
    U = '32',
    v = '9',
    V = '9',
    w = '13',
    W = '13',
    x = '7',
    X = '7',
    y = '16',
    z = '6',
    Z = '6',
    ',' = '43',
    ArrowUp = '126',
    Home = '115',
    Tab = '48',
    Number1 = '18',
    Number2 = '19',
    Number3 = '20',
    Number4 = '21',
    Number6 = '22',
    Number7 = '26',
    Number8 = '28',
    Number9 = '25',
    Number0 = '29',
    Enter = '36',
    ESC = '53',
}